version: "3.8"

services:
  dummy1:
    image: agung1ds/dummy-project:1.2
    container_name: dummy1
    ports:
      - 81:80
    networks:
      nginx_network:
        ipv4_address: "10.10.0.6"
  
  dummy2:
    image: agung1ds/dummy-project:1.3
    container_name: dummy2
    ports:
      - 82:80
    networks:
      nginx_network:
        ipv4_address: "10.10.0.7"

  nginx-proxy:
    image: nginx
    container_name: nginx-proxy
    ports:
      - 80:80
    depends_on:
      - dummy1
      - dummy2
    links:
      - "dummy1"
      - "dummy2"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      nginx_network:
        ipv4_address: "10.10.0.8"
    
networks:
  nginx_network:
    driver: bridge
    ipam:
      config:
        - subnet: 10.10.0.0/16
          gateway: 10.10.0.1
